/** Source-backed customer-console page contracts (specs/02_ui/console_experience.md). */
export const PAGE_CONTRACTS = Object.freeze({
  dashboard: Object.freeze({ purpose: 'Tenant-scoped health and activity overview', personas: ['tenant_admin', 'operator'], permission: 'console.read', data_classification: 'operational_metadata', kpis: ['projection_watermark', 'ingestion_status'], widgets: ['health_summary', 'recent_activity'], tables: [], filters: ['time_range'], actions: ['open_search'], bulk_limit: 0, states: ['loading', 'success', 'empty', 'forbidden', 'error'], api: 'GET /v1/console/dashboard', events: [], audit: 'read-only access is audited', performance_budget_ms: 1000, accessibility: 'landmarks, labelled status, keyboard navigation', documentation: 'specs/02_ui/console_experience.md', acceptance: 'tenant-scoped synthetic response renders without financial payloads', non_goals: ['mutating account or transaction state'] }),
  data: Object.freeze({ purpose: 'Inspect tenant data quality and projection freshness', personas: ['tenant_admin', 'data_steward'], permission: 'console.data.read', data_classification: 'operational_metadata', kpis: ['indexed_count', 'quarantine_count', 'freshness_seconds'], widgets: ['projection_freshness', 'quality_summary'], tables: ['data_quality'], filters: ['status'], actions: ['open_search'], bulk_limit: 0, states: ['loading', 'success', 'empty', 'forbidden', 'error'], api: 'GET /v1/console/data', events: [], audit: 'read-only access is audited', performance_budget_ms: 1000, accessibility: 'table headers and live status', documentation: 'specs/02_ui/console_experience.md', acceptance: 'tenant-scoped synthetic response renders classification and freshness', non_goals: ['editing canonical facts', 'bulk mutation'] }),
  'search-workbench': Object.freeze({ purpose: 'Tenant-scoped evidence-backed transaction search', personas: ['tenant_admin', 'operator'], permission: 'search.read', data_classification: 'redacted_metadata', kpis: ['result_count', 'projection_watermark'], widgets: ['query_input', 'result_summary'], tables: ['redacted_search_results'], filters: ['query'], actions: ['open_evidence'], bulk_limit: 0, states: ['loading', 'success', 'empty', 'forbidden', 'error', 'unavailable'], api: 'GET /v1/console/search-workbench', events: [], audit: 'read-only search access is audited', performance_budget_ms: 1000, accessibility: 'labelled search and live result status', documentation: 'specs/02_ui/console_experience.md', acceptance: 'authorization-derived results exclude amount and account identifiers', non_goals: ['client-supplied tenant scope', 'unredacted financial fields'] }),
  evidence: Object.freeze({ purpose: 'Tenant-scoped provenance inspection', personas: ['tenant_admin', 'operator'], permission: 'evidence.read', data_classification: 'redacted_metadata', kpis: ['evidence_count'], widgets: ['evidence_summary'], tables: ['evidence_metadata'], filters: ['record_id'], actions: [], bulk_limit: 0, states: ['loading', 'success', 'empty', 'forbidden', 'error', 'unavailable'], api: 'GET /v1/console/evidence', events: [], audit: 'read-only evidence access is audited', performance_budget_ms: 1000, accessibility: 'labelled provenance metadata and live status', documentation: 'specs/02_ui/console_experience.md', acceptance: 'authorization-derived evidence metadata renders with unavailable state', non_goals: ['raw artifact rendering', 'client-supplied tenant scope'] })
});
export const NAVIGATION = Object.freeze([
  ['Overview', ['dashboard']], ['Platform', ['platform']], ['Data', ['data']], ['Search', ['search']],
  ['AI', ['ai']], ['Workflows', ['workflows']], ['Governance', ['governance']], ['Developers', ['developers']], ['Operations', ['operations']]
]);

export function createConsoleApi({ fetchImpl = globalThis.fetch, baseUrl = '' } = {}) {
  if (typeof fetchImpl !== 'function') throw new TypeError('fetch implementation is required');
  const get = async (path, signal) => {
    const response = await fetchImpl(`${baseUrl}${path}`, { credentials: 'include', headers: { accept: 'application/json' }, signal });
    let body = {}; try { body = await response.json(); } catch { /* empty body */ }
    if (!response.ok) { const error = new Error(response.status === 403 ? 'console_forbidden' : 'console_unavailable'); error.status = response.status; error.code = body?.code; throw error; }
    return body;
  };
  return { dashboard: ({ signal } = {}) => get('/v1/console/dashboard', signal), data: ({ signal } = {}) => get('/v1/console/data', signal), 'search-workbench': ({ signal } = {}) => get('/v1/console/search-workbench', signal), evidence: ({ signal } = {}) => get('/v1/console/evidence', signal) };
}

export function createConsoleShell({ root, api, initialPage = 'dashboard' } = {}) {
  if (!root || typeof root.replaceChildren !== 'function') throw new TypeError('root element is required');
  if (!api) throw new TypeError('console API is required');
  const state = { page: initialPage, status: 'idle', payload: null, error: null };
  const render = () => { root.replaceChildren(); const nav = document.createElement('nav'); nav.setAttribute('aria-label', 'Customer console'); for (const [group, pages] of NAVIGATION) { const section = document.createElement('section'); const label = document.createElement('h2'); label.textContent = group; section.append(label); for (const id of pages) { const button = document.createElement('button'); button.type = 'button'; button.textContent = id === 'dashboard' ? 'Overview' : id[0].toUpperCase() + id.slice(1); button.setAttribute('aria-current', state.page === id ? 'page' : 'false'); button.addEventListener('click', () => { state.page = id; load(); }); section.append(button); } nav.append(section); } root.append(nav); const main = document.createElement('main'); const contract = PAGE_CONTRACTS[state.page]; const heading = document.createElement('h1'); heading.textContent = contract?.purpose || `${state.page[0].toUpperCase()}${state.page.slice(1)} (planned)`; main.append(heading); const status = document.createElement('p'); status.setAttribute('role', 'status'); status.setAttribute('aria-live', 'polite'); status.textContent = state.status === 'loading' ? 'Loading...' : state.status === 'error' ? (state.error?.status === 403 ? 'You do not have permission to view this page.' : 'Unable to load this page.') : state.status === 'empty' ? 'No data available.' : state.status === 'success' ? 'Data loaded.' : contract ? 'Ready.' : 'This page is specified in the console roadmap but its API is not available in this environment.'; main.append(status); if (contract) { const meta = document.createElement('dl'); for (const [key, value] of [['Permission', contract.permission], ['Classification', contract.data_classification], ['KPIs', contract.kpis.join(', ')], ['Widgets', contract.widgets.join(', ')], ['Tables', contract.tables.join(', ') || 'None'], ['States', contract.states.join(', ')], ['API', contract.api], ['Non-goals', contract.non_goals.join('; ')]]) { const dt = document.createElement('dt'); dt.textContent = key; const dd = document.createElement('dd'); dd.textContent = value; meta.append(dt, dd); } main.append(meta); } root.append(main); };
  const load = async () => { if (!api[state.page]) { state.status = 'idle'; render(); return; } state.status = 'loading'; state.error = null; render(); try { state.payload = await api[state.page](); state.status = state.payload?.data?.length === 0 ? 'empty' : 'success'; } catch (error) { state.status = 'error'; state.error = { status: error.status, code: error.code }; } render(); };
  render(); return { load, snapshot: () => ({ ...state }) };
}
