import test from 'node:test';
import assert from 'node:assert/strict';
import { ManagedControlError, SyntheticSecretProvider, SyntheticConfigProvider, SyntheticSigningKeyProvider, loadManagedEnvironment, signReleaseManifest, verifyReleaseManifest, protectedPromotionGate } from './managed-controls.mjs';

const refs = { secretRef: 'secret://upfs/pilot/signing', configRef: 'config://upfs/pilot', signingKeyRef: 'key://upfs/pilot/release' };
const synthetic = () => ({ secretProvider: new SyntheticSecretProvider({ [refs.secretRef]: { value: 's'.repeat(48), version: 'v1' } }), configProvider: new SyntheticConfigProvider({ [refs.configRef]: { version: 'v1', region: 'synthetic' } }), signingKeyProvider: new SyntheticSigningKeyProvider({ [refs.signingKeyRef]: { value: 'k'.repeat(48), version: 'v1' } }) });

test('non-managed environments do not require provider credentials', async () => { assert.deepEqual(await loadManagedEnvironment({ environment: 'test' }), { environment: 'test', managed: false, synthetic_only: true, config: {} }); });
test('pilot fails closed on missing refs and synthetic provider', async () => { await assert.rejects(loadManagedEnvironment({ environment: 'pilot' }), (e) => e.code === 'managed_references_required'); await assert.rejects(loadManagedEnvironment({ environment: 'pilot', ...refs, ...synthetic() }), (e) => e.code === 'synthetic_provider_forbidden'); });
test('production rejects expired and undersized managed secrets', async () => { const providers = synthetic(); providers.secretProvider = new SyntheticSecretProvider({ [refs.secretRef]: { value: 'short', version: 'v1' } }); await assert.rejects(loadManagedEnvironment({ environment: 'production', ...refs, ...providers }), (e) => e.code === 'synthetic_provider_forbidden'); });
test('managed key rotation metadata is enforced at expiry', async () => { const provider = { async getSecret() { return { reference: refs.secretRef, environment: 'pilot', provider: 'vault', value: 's'.repeat(48), version: 'v2', rotation_due: '2020-01-01T00:00:00Z', synthetic_only: false }; } }; const configProvider = { async getConfig() { return { reference: refs.configRef, environment: 'pilot', provider: 'vault', config: {}, version: 'v1', synthetic_only: false }; } }; const signingKeyProvider = { async getSigningKey() { return { reference: refs.signingKeyRef, environment: 'pilot', provider: 'vault', value: 'k'.repeat(48), version: 'v1', synthetic_only: false }; } }; await assert.rejects(loadManagedEnvironment({ environment: 'pilot', ...refs, secretProvider: provider, configProvider, signingKeyProvider }), (e) => e.code === 'secret_rotation_due'); });
test('signing rejects arbitrary caller secrets and binds metadata to managed material', () => { assert.throws(() => signReleaseManifest('{"release":"x"}', { value: 's'.repeat(48) }), /environment-bound managed signing material/); const material = { value: 's'.repeat(48), provider: 'vault', reference: refs.signingKeyRef, version: 'v1', environment: 'pilot', secret_reference: refs.secretRef, config_reference: refs.configRef }; const sig = signReleaseManifest('{"release":"x"}', material); assert.match(sig.signature, /^[a-f0-9]{64}$/); assert.equal(sig.metadata.environment, 'pilot'); assert.equal(verifyReleaseManifest('{"release":"x"}', sig, material), true); assert.equal(verifyReleaseManifest('{"release":"y"}', sig, material), false); assert.equal(verifyReleaseManifest('{"release":"x"}', sig, { ...material, environment: 'production' }), false); });
test('provider responses cannot cross environments or references', async () => { const managed = { async getSecret() { return { reference: 'secret://other', environment: 'pilot', value: 's'.repeat(48), version: 'v1', provider: 'vault', synthetic_only: false }; }, async getConfig() { return { reference: refs.configRef, environment: 'pilot', config: {}, version: 'v1', provider: 'vault', synthetic_only: false }; }, async getSigningKey() { return { reference: refs.signingKeyRef, environment: 'pilot', value: 'k'.repeat(48), version: 'v1', provider: 'vault', synthetic_only: false }; } }; await assert.rejects(loadManagedEnvironment({ environment: 'pilot', ...refs, secretProvider: managed, configProvider: managed, signingKeyProvider: managed }), (e) => e.code === 'provider_reference_mismatch'); });
test('promotion requires matching target managed signature metadata', () => { const managed = { managed: true, signing_key_reference: refs.signingKeyRef, signing_key_version: 'v1', signing_material: { provider: 'vault' } }; const base = { environment: 'pilot', managed, approval: { approved: true, approver: 'release-owner', evidence: 'change-123', expires_at: '2099-01-01T00:00:00Z' }, artifact: { immutable: true, signature_verified: true, signing_key_reference: refs.signingKeyRef, signing_key_version: 'v1', signature_provider: 'vault', signature_environment: 'pilot' }, health: { passed: true }, reconciliation: { zero_drift: true } }; assert.equal(protectedPromotionGate({ ...base, approval: false }).allowed, false); assert.equal(protectedPromotionGate(base).allowed, true); assert.equal(protectedPromotionGate({ ...base, artifact: { ...base.artifact, signature_environment: 'production' } }).allowed, false); assert.equal(protectedPromotionGate({ ...base, reconciliation: { zero_drift: false } }).allowed, false); });
