import test from 'node:test';
import assert from 'node:assert/strict';
import { ManagedControlError, SyntheticSecretProvider, SyntheticConfigProvider, SyntheticSigningKeyProvider, loadManagedEnvironment, signReleaseManifest, verifyReleaseManifest, protectedPromotionGate } from './managed-controls.mjs';

const refs = { secretRef: 'secret://upfs/pilot/signing', configRef: 'config://upfs/pilot', signingKeyRef: 'key://upfs/pilot/release' };
const synthetic = () => ({ secretProvider: new SyntheticSecretProvider({ [refs.secretRef]: { value: 's'.repeat(48), version: 'v1' } }), configProvider: new SyntheticConfigProvider({ [refs.configRef]: { version: 'v1', region: 'synthetic' } }), signingKeyProvider: new SyntheticSigningKeyProvider({ [refs.signingKeyRef]: { value: 'k'.repeat(48), version: 'v1' } }) });

test('non-managed environments do not require provider credentials', async () => { assert.deepEqual(await loadManagedEnvironment({ environment: 'test' }), { environment: 'test', managed: false, synthetic_only: true, config: {} }); });
test('pilot fails closed on missing refs and synthetic provider', async () => { await assert.rejects(loadManagedEnvironment({ environment: 'pilot' }), (e) => e.code === 'managed_references_required'); await assert.rejects(loadManagedEnvironment({ environment: 'pilot', ...refs, ...synthetic() }), (e) => e.code === 'synthetic_provider_forbidden'); });
test('production rejects expired and undersized managed secrets', async () => { const providers = synthetic(); providers.secretProvider = new SyntheticSecretProvider({ [refs.secretRef]: { value: 'short', version: 'v1' } }); await assert.rejects(loadManagedEnvironment({ environment: 'production', ...refs, ...providers }), (e) => e.code === 'synthetic_provider_forbidden'); });
test('managed key rotation metadata is enforced at expiry', async () => { const provider = { async getSecret() { return { value: 's'.repeat(48), version: 'v2', rotation_due: '2020-01-01T00:00:00Z', synthetic_only: false }; } }; const configProvider = { async getConfig() { return { config: {}, version: 'v1', synthetic_only: false }; } }; const signingKeyProvider = { async getSigningKey() { return { value: 'k'.repeat(48), version: 'v1', synthetic_only: false }; } }; await assert.rejects(loadManagedEnvironment({ environment: 'pilot', ...refs, secretProvider: provider, configProvider, signingKeyProvider }), (e) => e.code === 'secret_rotation_due'); });
test('signing rejects arbitrary caller secrets and accepts provider material', async () => { assert.throws(() => signReleaseManifest('{"release":"x"}', { value: 's'.repeat(48) }), /managed signing material/); const loaded = await loadManagedEnvironment({ environment: 'test' }); const material = { value: 's'.repeat(48), provider: 'managed', reference: refs.signingKeyRef, version: 'v1' }; const sig = signReleaseManifest('{"release":"x"}', material); assert.match(sig, /^[a-f0-9]{64}$/); assert.equal(verifyReleaseManifest('{"release":"x"}', sig, material), true); assert.equal(verifyReleaseManifest('{"release":"y"}', sig, material), false); });
test('promotion requires expiring approval evidence, immutable signature, health, and reconciliation', () => { const base = { environment: 'pilot', approval: { approved: true, approver: 'release-owner', evidence: 'change-123', expires_at: '2099-01-01T00:00:00Z' }, artifact: { immutable: true, signature_verified: true, signing_key_reference: refs.signingKeyRef }, health: { passed: true }, reconciliation: { zero_drift: true } }; assert.equal(protectedPromotionGate({ ...base, approval: false }).allowed, false); assert.equal(protectedPromotionGate(base).allowed, true); assert.equal(protectedPromotionGate({ ...base, reconciliation: { zero_drift: false } }).allowed, false); assert.equal(protectedPromotionGate({ ...base, environment: 'sandbox' }).allowed, false); });
