import test from 'node:test';
import assert from 'node:assert/strict';
import { PolicyWorkflowService } from './policy-workflow.mjs';

const actor = { issuer: 'issuer', subject: 'alice' }, other = { issuer: 'issuer', subject: 'bob' };
const auth = (a, t, e, p) => a?.subject === 'alice' && t === 't1' && e === 'e1';
const service = () => new PolicyWorkflowService({ authorize: auth, requestId: (() => { let n = 0; return () => `req-${++n}`; })() });
const policy = { id: 'payments', rules: [{ action: 'workflow:create', effect: 'allow' }, { action: 'workflow:approve', effect: 'allow' }, { action: 'workflow:read', effect: 'allow' }, { action: 'workflow:execute', effect: 'allow' }] };
const workflow = { id: 'w1', tenant_id: 't1', environment_id: 'e1', steps: [{ id: 'charge', classification: 'irreversible' }], approval: { required: 1 } };

test('policy decisions are explicit, versioned, and deny by default', () => { const s = service(); assert.equal(s.evaluate({ actor, tenantId: 't1', environmentId: 'e1', action: 'workflow:create' }).body.reason_code, 'no_policy'); s.publishPolicy({ actor, tenantId: 't1', environmentId: 'e1', policy, idempotencyKey: 'policy-key-123456' }); const d = s.evaluate({ actor, tenantId: 't1', environmentId: 'e1', action: 'workflow:create', attributes: { purpose: 'test' } }); assert.equal(d.status, 200); assert.equal(d.body.decision, 'allow'); assert.equal(d.body.policy_version, 'payments:1'); assert.deepEqual(d.body.evaluated_attributes, { purpose: 'test' }); });
test('cross-tenant and unauthenticated requests cannot publish or inspect', () => { const s = service(); assert.equal(s.publishPolicy({ actor: other, tenantId: 't1', environmentId: 'e1', policy, idempotencyKey: 'policy-key-123456' }).status, 403); assert.equal(s.evaluate({ actor, tenantId: 't2', environmentId: 'e1', action: 'x' }).status, 403); });
test('workflow requires idempotency, approval quorum, and optimistic concurrency', () => { const s = service(); s.publishPolicy({ actor, tenantId: 't1', environmentId: 'e1', policy, idempotencyKey: 'policy-key-123456' }); const c = s.createWorkflow({ actor, tenantId: 't1', environmentId: 'e1', workflow: { ...workflow, approval: { required: 2 } }, idempotencyKey: 'workflow-key-123456' }); assert.equal(c.status, 201); assert.equal(s.createWorkflow({ actor, tenantId: 't1', environmentId: 'e1', workflow, idempotencyKey: 'short' }).status, 400); assert.equal(s.transition({ actor, tenantId: 't1', environmentId: 'e1', workflowId: 'w1', status: 'running', ifMatch: '"1"' }).body.code, 'approval_required'); const a = s.approve({ actor, tenantId: 't1', environmentId: 'e1', workflowId: 'w1', decision: 'approve', ifMatch: '"1"' }); assert.equal(a.body.status, 'pending_approval'); assert.equal(s.approve({ actor, tenantId: 't1', environmentId: 'e1', workflowId: 'w1', decision: 'approve', ifMatch: '"1"' }).status, 412); });
test('deny approval blocks execution and audit/history are append-only', () => { const s = service(); s.publishPolicy({ actor, tenantId: 't1', environmentId: 'e1', policy, idempotencyKey: 'policy-key-123456' }); s.createWorkflow({ actor, tenantId: 't1', environmentId: 'e1', workflow, idempotencyKey: 'workflow-key-123456' }); const a = s.approve({ actor, tenantId: 't1', environmentId: 'e1', workflowId: 'w1', decision: 'deny', reason: 'test', ifMatch: '"1"' }); assert.equal(a.body.status, 'denied'); assert.equal(s.transition({ actor, tenantId: 't1', environmentId: 'e1', workflowId: 'w1', status: 'running', ifMatch: '"2"' }).body.code, 'approval_required'); assert.equal(s.history('w1').length, 2); assert.ok(s.audit().some((x) => x.action === 'workflow.approve')); });
