import test from "node:test";
import assert from "node:assert/strict";
import { PostgresOutboxAdapter, PostgresCheckpointAdapter, recoverOutbox } from "./transaction-outbox.mjs";

class FakePg {
  constructor() { this.events = new Map(); this.checkpoints = new Map(); this.scopes = []; this.failQuery = false; }
  async transaction(work, { tenantId } = {}) { if (!tenantId) throw new Error("tenant scope is required"); this.scopes.push(tenantId); return work({ query: this.query.bind(this) }); }
  async query(sql, values = []) {
    if (this.failQuery) throw new Error("synthetic database outage");
    if (sql.startsWith("INSERT INTO transactional_outbox")) { const [id, tenant, aggregate, type, payload, fingerprint, idem, occurred] = values; const key = `${tenant}|${idem}`; const existing = [...this.events.values()].find((e) => `${e.tenant_id}|${e.idempotency_key}` === key); if (existing) return existing.payload_fingerprint === fingerprint ? { rows: [existing] } : { rows: [] }; const e = { id, tenant_id: tenant, aggregate_id: aggregate, event_type: type, payload, payload_fingerprint: fingerprint, idempotency_key: idem, occurred_at: occurred, event_sequence: this.events.size + 1, status: "pending", attempts: 0, available_at: new Date(0).toISOString() }; this.events.set(id, e); return { rows: [e] }; }
    if (sql.startsWith("WITH candidates")) { const [tenant, limit, consumer] = values; const rows = [...this.events.values()].filter((e) => e.tenant_id === tenant && ["pending", "failed"].includes(e.status) && e.attempts < values[3]).sort((a,b) => a.event_sequence-b.event_sequence).slice(0, limit); rows.forEach((e) => { e.status = "claimed"; e.consumer = consumer; e.lease_until = values[4]; e.attempts += 1; }); return { rows }; }
    if (sql.startsWith("UPDATE transactional_outbox SET status='acknowledged'")) { const [tenant, id, consumer] = values; const e = this.events.get(id); if (!e || e.tenant_id !== tenant || e.consumer !== consumer || e.status !== "claimed") return { rows: [] }; e.status = "acknowledged"; e.lease_until = null; return { rows: [{ id }] }; }
    if (sql.startsWith("UPDATE transactional_outbox SET status=CASE")) { const [tenant, id, consumer, max, failure, next] = values; const e = this.events.get(id); if (!e || e.tenant_id !== tenant || e.consumer !== consumer || e.status !== "claimed") return { rows: [] }; e.status = e.attempts >= max ? "dead_letter" : "failed"; e.last_error = failure; e.available_at = next; e.lease_until = null; return { rows: [{ id, status: e.status, attempts: e.attempts }] }; }
    if (sql.startsWith("SELECT tenant_id, consumer")) { const [tenant, consumer] = values; const e = this.checkpoints.get(`${tenant}|${consumer}`); return { rows: e ? [e] : [] }; }
    if (sql.startsWith("INSERT INTO durable_checkpoints")) { const [tenant, consumer, sequence] = values; const key = `${tenant}|${consumer}`; const prior = this.checkpoints.get(key); const e = { tenant_id: tenant, consumer, sequence: Math.max(prior?.sequence ?? 0, sequence) }; this.checkpoints.set(key, e); return { rows: [e] }; }
    throw new Error(`unhandled SQL: ${sql}`);
  }
}

test("outbox append is tenant-scoped and idempotent", async () => { const pg = new FakePg(); const outbox = new PostgresOutboxAdapter({ postgres: pg }); const args = { tenantId: "t1", eventId: "e1", type: "transaction.created", payload: { id: "tx1" }, idempotencyKey: "k1", occurredAt: "2026-01-01T00:00:00Z" }; const a = await outbox.append(args); const b = await outbox.append(args); assert.equal(a.id, b.id); await assert.rejects(() => outbox.append({ ...args, payload: { id: "tx2" } }), /idempotency conflict/); assert.deepEqual(pg.scopes, ["t1", "t1", "t1"]); });
test("claim ownership, ack, failure retry and dead letter are enforced", async () => { const pg = new FakePg(); const outbox = new PostgresOutboxAdapter({ postgres: pg, maxAttempts: 2 }); await outbox.append({ tenantId: "t1", eventId: "e1", type: "x", payload: {} }); const claimed = await outbox.claim({ tenantId: "t1", consumer: "c1" }); assert.equal(claimed.length, 1); await assert.rejects(() => outbox.acknowledge({ tenantId: "t1", eventId: "e1", consumer: "c2" })); await outbox.fail({ tenantId: "t1", eventId: "e1", consumer: "c1" }); const claimed2 = await outbox.claim({ tenantId: "t1", consumer: "c1" }); await outbox.fail({ tenantId: "t1", eventId: "e1", consumer: "c1" }); assert.equal(pg.events.get("e1").status, "dead_letter"); assert.equal(claimed2.length, 1); });
test("checkpoint is monotonic and tenant isolated", async () => { const pg = new FakePg(); const cp = new PostgresCheckpointAdapter({ postgres: pg }); await cp.save({ tenantId: "t1", consumer: "c", sequence: 9 }); await cp.save({ tenantId: "t1", consumer: "c", sequence: 3 }); assert.equal((await cp.load({ tenantId: "t1", consumer: "c" })).sequence, 9); assert.equal((await cp.load({ tenantId: "t2", consumer: "c" })).sequence, 0); });
test("recovery acknowledges before checkpoint and retries handler failures", async () => { const pg = new FakePg(); const outbox = new PostgresOutboxAdapter({ postgres: pg }); const cp = new PostgresCheckpointAdapter({ postgres: pg }); await outbox.append({ tenantId: "t1", eventId: "e1", type: "x", payload: { safe: true } }); let calls = 0; const result = await recoverOutbox({ outbox, checkpoint: cp, tenantId: "t1", consumer: "c", handle: async () => { calls += 1; return { ok: true }; } }); assert.equal(result.results[0].status, "acknowledged"); assert.equal(calls, 1); assert.equal((await cp.load({ tenantId: "t1", consumer: "c" })).sequence, 1); await outbox.append({ tenantId: "t1", eventId: "e2", type: "x", payload: {} }); const failed = await recoverOutbox({ outbox, checkpoint: cp, tenantId: "t1", consumer: "c", handle: async () => { throw new Error("boom"); } }); assert.equal(failed.results[0].status, "failed"); assert.equal(pg.events.get("e2").status, "failed"); });
test("recovery ignores an already checkpointed event without invoking handler", async () => { const pg = new FakePg(); const outbox = new PostgresOutboxAdapter({ postgres: pg }); const cp = new PostgresCheckpointAdapter({ postgres: pg }); await outbox.append({ tenantId: "t1", eventId: "e1", type: "x", payload: {} }); await cp.save({ tenantId: "t1", consumer: "c", sequence: 9 }); let calls = 0; const result = await recoverOutbox({ outbox, checkpoint: cp, tenantId: "t1", consumer: "c", handle: async () => { calls += 1; } }); assert.equal(result.results[0].status, "ignored"); assert.equal(calls, 0); assert.equal((await cp.load({ tenantId: "t1", consumer: "c" })).sequence, 9); });
test("missing durable dependencies fail closed", () => { assert.throws(() => new PostgresOutboxAdapter(), /postgres adapter is required/); assert.throws(() => new PostgresCheckpointAdapter(), /postgres adapter is required/); });
