import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { evaluateAuthorization } from './task-0020-authorization.mjs';

const files = {
  'artifacts/task-0017-pg14-native-report.json': { status: 'passed', native_evidence: true, generated_at: '2026-07-30T00:00:00Z' },
  'artifacts/task-0015-release-report.json': { status: 'passed', manifest: 'artifacts/fixture-manifest.json', release_id: 'synthetic-abc', external_deployment: 'not-performed', generated_at: '2026-07-30T00:00:00Z' },
  'artifacts/task-0018-controls-report.json': { status: 'passed', generated_at: '2026-07-30T00:00:00Z' },
  'artifacts/task-0019-pilot-report.json': { status: 'passed', synthetic_only: true, production_deployment: 'not-performed', external_contact: 'not-performed', generated_at: '2026-07-30T00:00:00Z' },
  'docs/compliance/control-library.json': { schema_version: 'controls' },
  'docs/runbooks/controlled-pilot-runbook.md': 'runbook'
};
function fixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'upfs-task-0020-')); for (const [file, value] of Object.entries(files)) { const target = path.join(root, file); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, typeof value === 'string' ? value : JSON.stringify(value)); } const rel = 'artifacts/task-0017-pg14-native-report.json'; const body = { schema_version: 'upfs.release.v1', release_id: 'fixture', artifact: { entries: { [rel]: { sha256: crypto.createHash('sha256').update(fs.readFileSync(path.join(root, rel))).digest('hex') } } } }; body.manifest_sha256 = crypto.createHash('sha256').update(JSON.stringify(body)).digest('hex'); fs.writeFileSync(path.join(root, 'artifacts/fixture-manifest.json'), JSON.stringify(body)); return root; }
const complete = { decision: 'GO', as_of: '2026-07-31T00:00:00Z', evidence_max_age_ms: 7 * 24 * 60 * 60 * 1000, approvals: Object.fromEntries(['release_approver', 'security_approver', 'data_owner', 'incident_commander', 'external_deployment'].map((name) => [name, { approved: true, name: 'named-approver', identity: 'approver-id', scope: name === 'external_deployment' ? 'pilot deployment' : 'release review', reason: 'synthetic gate review', reference: 'approval-ref', date: '2026-07-30T00:00:00Z', expires_at: '2026-08-01T00:00:00Z', ...(name === 'external_deployment' ? { dual_control: true } : {}) }])), risks: [{ id: 'R-1', owner: 'security', status: 'accepted', mitigation: 'pause and remediate' }], slos: [{ signal: 'availability', objective: '>=99%', pause_threshold: '<99%' }], rollback: { strategy: 'corrective-forward', owner: 'release', trigger: 'failed health gate', verification: 'reconciliation' } };
test('fails closed with missing evidence and approvals', () => { const root = fixture(); fs.rmSync(path.join(root, 'artifacts/task-0017-pg14-native-report.json')); const report = evaluateAuthorization({ root, authorization: {} }); assert.equal(report.decision, 'NO-GO'); assert.ok(report.checks.some((c) => c.name === 'evidence-native-postgres' && c.status === 'failed')); fs.rmSync(root, { recursive: true, force: true }); });
test('complete package can reach GO only with explicit approvals and all gates', () => { const root = fixture(); const report = evaluateAuthorization({ root, authorization: complete }); assert.equal(report.decision, 'GO'); assert.equal(report.production_deployment, 'not-performed'); fs.rmSync(root, { recursive: true, force: true }); });
test('tampered or non-passed native evidence cannot authorize', () => { const root = fixture(); fs.writeFileSync(path.join(root, 'artifacts/task-0017-pg14-native-report.json'), JSON.stringify({ status: 'passed', native_evidence: false })); const report = evaluateAuthorization({ root, authorization: complete }); assert.equal(report.decision, 'NO-GO'); assert.ok(report.checks.some((c) => c.name === 'native-evidence' && c.status === 'failed')); fs.rmSync(root, { recursive: true, force: true }); });
test('CLI invocation uses a Windows-safe main guard and writes a report', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'upfs-task-0020-cli-')); const result = spawnSync(process.execPath, [path.resolve('scripts/task-0020-authorization.mjs')], { cwd: root, encoding: 'utf8' }); assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`); assert.match(result.stdout, /TASK-0020 authorization evaluated: NO-GO/); assert.equal(JSON.parse(fs.readFileSync(path.join(root, 'artifacts/task-0020-authorization-report.json'))).decision, 'NO-GO'); fs.rmSync(root, { recursive: true, force: true }); });
