const MAX_LIMIT = 100;

function safeError(response, body) {
  const error = new Error(body?.code || `admin_request_failed_${response.status}`);
  error.status = response.status; error.code = body?.code; error.retryable = response.status >= 500;
  return error;
}

/** Contract-bound adapter. The UI only consumes redacted /admin/v1 responses. */
export function createAdminApi({ fetchImpl = globalThis.fetch, baseUrl = '', supportSession = null } = {}) {
  if (typeof fetchImpl !== 'function') throw new TypeError('fetch implementation is required');
  const request = async (path, options = {}) => {
    const headers = { accept: 'application/json', ...(options.body ? { 'content-type': 'application/json' } : {}), ...(supportSession ? { 'X-Support-Session': supportSession } : {}) };
    const response = await fetchImpl(`${baseUrl}${path}`, { credentials: 'include', ...options, headers: { ...headers, ...(options.headers || {}) } });
    let body = {}; try { body = await response.json(); } catch { /* empty */ }
    if (!response.ok) throw safeError(response, body);
    return body;
  };
  return {
    health: () => request('/admin/v1/health'),
    tenants: ({ limit = 25, cursor = null } = {}) => request(`/admin/v1/tenants?limit=${Math.min(MAX_LIMIT, Math.max(1, limit))}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`),
    tenant: (id) => request(`/admin/v1/tenants/${encodeURIComponent(id)}`),
    managedIntegrations: ({ tenantId, environmentId }) => request(`/admin/v1/managed-integrations?tenant_id=${encodeURIComponent(tenantId)}&environment_id=${encodeURIComponent(environmentId)}`),
    operations: ({ tenantId, environmentId } = {}) => request(`/admin/v1/operations?tenant_id=${encodeURIComponent(tenantId)}${environmentId ? `&environment_id=${encodeURIComponent(environmentId)}` : ''}`),
    createOperation: ({ tenantId, environmentId, type, reason, dryRun = true, changeTicket, idempotencyKey }) => request('/admin/v1/operations', { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey }, body: JSON.stringify({ tenant_id: tenantId, environment_id: environmentId, type, reason, dry_run: dryRun, change_ticket: changeTicket }) }),
    approveOperation: ({ operationId, reason, dualControl = false, idempotencyKey }) => request(`/admin/v1/operations/${encodeURIComponent(operationId)}/approve`, { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey }, body: JSON.stringify({ reason, dual_control: dualControl }) }),
    executeOperation: ({ operationId, idempotencyKey }) => request(`/admin/v1/operations/${encodeURIComponent(operationId)}/execute`, { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey } }),
    rollbackOperation: ({ operationId, evidence, idempotencyKey }) => request(`/admin/v1/operations/${encodeURIComponent(operationId)}/rollback`, { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey }, body: JSON.stringify({ evidence }) }),
    module: (name) => { const allowed = new Set(['support-access','ingestion','canonical-quality','search-projections','redis','ai-ops','workflows','policy-simulator','security','compliance','releases','incidents','audit','operations']); if (!allowed.has(name)) throw Object.assign(new Error('unsupported_admin_module'), { code: 'unsupported_admin_module', status: 400 }); return request(`/admin/v1/${name}`); }
  };
}

const text = (value) => String(value ?? '');
const el = (tag, content) => { const node = document.createElement(tag); if (content !== undefined) node.textContent = content; return node; };

export function createAdminConsole({ root, api } = {}) {
  if (!root || typeof root.replaceChildren !== 'function') throw new TypeError('root element is required');
  if (!api || typeof api.health !== 'function') throw new TypeError('admin API is required');
  // This list mirrors specs/14_admin_control_plane. Names are API route identifiers.
  const modules = ['support-access', 'ingestion', 'canonical-quality', 'search-projections', 'redis', 'ai-ops', 'workflows', 'policy-simulator', 'security', 'compliance', 'releases', 'incidents', 'audit', 'operations'];
  const state = { view: 'dashboard', status: 'idle', health: null, tenants: [], selected: null, moduleData: {}, integration: null, operations: [], operationResults: [], error: null };
  const render = () => {
    root.replaceChildren();
    const heading = el('h1', 'UPFS administration'); root.append(heading);
    const nav = el('nav'); nav.setAttribute('aria-label', 'Administration');
    [['dashboard', 'Dashboard'], ['tenants', 'Tenants'], ['health', 'Platform health'], ...modules.map((name) => [name, name.replace('-', ' ')])].forEach(([id, label]) => { const button = el('button', label); button.type = 'button'; button.setAttribute('aria-current', state.view === id ? 'page' : 'false'); button.addEventListener('click', () => { state.view = id; state.error = null; render(); load(); }); nav.append(button); }); root.append(nav);
    const status = el('p'); status.setAttribute('role', 'status'); status.setAttribute('aria-live', 'polite'); status.textContent = state.status === 'loading' ? 'Loading administrative metadata…' : state.error ? (state.error.status === 403 ? 'You do not have permission to view this administrative data.' : 'Administrative data is temporarily unavailable.') : ''; root.append(status);
    const main = el('main'); main.setAttribute('aria-label', state.view); root.append(main);
    if (state.view === 'dashboard') renderDashboard(main); else if (state.view === 'tenants') renderTenants(main); else if (state.view === 'health') renderHealth(main); else if (state.view === 'operations') renderOperations(main); else renderModule(main, state.view);
  };
  const renderDashboard = (main) => { main.append(el('h2', 'Overview')); const cards = el('section'); cards.setAttribute('aria-label', 'Operational summary'); cards.append(el('p', `Platform: ${state.health?.status || 'Not loaded'}`), el('p', `Tenants loaded: ${state.tenants.length}`)); main.append(cards); };
  const renderHealth = (main) => { main.append(el('h2', 'Platform health')); if (!state.health) { main.append(el('p', 'No health observation loaded.')); return; } const table = el('table'); table.setAttribute('aria-label', 'Platform component health'); const head = el('tr'); ['Component', 'Status', 'Observed'].forEach((v) => { const th = el('th', v); th.scope = 'col'; head.append(th); }); const thead = el('thead'); thead.append(head); table.append(thead); const body = el('tbody'); Object.entries(state.health.components || {}).forEach(([name, value]) => { const row = el('tr'); [name, value.status, value.observed_at].forEach((v) => row.append(el('td', v))); body.append(row); }); table.append(body); main.append(table); };
  const field = (label, type = 'text', required = true) => { const wrap = el('label', label); const input = el('input'); input.type = type; input.required = required; input.name = label.toLowerCase().replace(/[^a-z]+/g, '_'); wrap.append(input); return { wrap, input }; };
  const renderOperations = (main) => {
    main.append(el('h2', 'Administrative operations'));
    main.append(el('p', 'All changes begin as synthetic dry runs. Production execution remains disabled without managed credentials and explicit external approval.'));
    const create = el('form'); create.setAttribute('aria-label', 'Create dry-run operation');
    const scope = field('Tenant and environment scope'); const type = field('Operation type'); const reason = field('Reason'); const ticket = field('Change ticket', 'text', false); const idem = field('Idempotency key');
    [scope.wrap, type.wrap, reason.wrap, ticket.wrap, idem.wrap].forEach((x) => create.append(x)); const submit = el('button', 'Create dry run'); submit.type = 'submit'; create.append(submit);
    create.addEventListener('submit', async (event) => { event.preventDefault(); state.error = null; try { const [tenantId, environmentId] = scope.input.value.split('/').map((v) => v.trim()); if (!tenantId || !environmentId || !reason.input.value.trim() || !idem.input.value.trim()) throw Object.assign(new Error('scope_reason_idempotency_required'), { code: 'scope_reason_idempotency_required', status: 400 }); const result = await api.createOperation({ tenantId, environmentId, type: type.input.value.trim(), reason: reason.input.value.trim(), dryRun: true, changeTicket: ticket.input.value.trim() || undefined, idempotencyKey: idem.input.value.trim() }); state.operationResults.unshift(result); await loadOperations(); } catch (error) { state.error = error; state.status = 'error'; render(); } }); main.append(create);
    const table = el('table'); table.setAttribute('aria-label', 'Administrative operation records'); const head = el('tr'); ['Operation', 'Scope', 'Status', 'Audit / rollback', 'Actions'].forEach((v) => { const th = el('th', v); th.scope = 'col'; head.append(th); }); const thead = el('thead'); thead.append(head); table.append(thead); const body = el('tbody');
    state.operations.forEach((op) => { const row = el('tr'); row.append(el('td', op.id), el('td', `${op.tenant_id || ''}/${op.environment_id || ''}`), el('td', op.status || 'unknown'), el('td', `audit ${op.audit?.length || 0}; rollback ${op.rollback?.evidence ? 'recorded' : 'none'}`)); const actions = el('td');
      const approve = el('button', 'Approve'); approve.type = 'button'; approve.disabled = op.status !== 'pending'; approve.addEventListener('click', () => thisApprove(op)); actions.append(approve);
      const execute = el('button', 'Execute'); execute.type = 'button'; execute.disabled = !(op.status === 'approved' && op.managed_credentials_available === true && op.external_approval === true); if (execute.disabled) execute.setAttribute('aria-label', 'Execute unavailable: managed credentials and external approval required'); execute.addEventListener('click', () => thisExecute(op)); actions.append(execute);
      const rollback = el('button', 'Rollback'); rollback.type = 'button'; rollback.disabled = !['approved', 'executed'].includes(op.status); rollback.addEventListener('click', () => thisRollback(op)); actions.append(rollback); row.append(actions); body.append(row); }); table.append(body); main.append(table);
    state.operationResults.slice(0, 5).forEach((result) => { const outcome = el('p', `Outcome: ${result?.operation?.status || result?.status || 'unknown'}`); outcome.setAttribute('role', 'status'); main.append(outcome); });
  };
  const thisApprove = async (op) => { const reason = globalThis.prompt ? globalThis.prompt('Approval reason (at least 10 characters)') : ''; const idem = globalThis.prompt ? globalThis.prompt('Idempotency key') : ''; if (!reason || !idem) return; try { state.operationResults.unshift(await api.approveOperation({ operationId: op.id, reason, dualControl: true, idempotencyKey: idem })); await loadOperations(); } catch (error) { state.error = error; render(); } };
  const thisExecute = async (op) => { const idem = globalThis.prompt ? globalThis.prompt('Idempotency key') : ''; if (!idem) return; try { state.operationResults.unshift(await api.executeOperation({ operationId: op.id, idempotencyKey: idem })); await loadOperations(); } catch (error) { state.error = error; render(); } };
  const thisRollback = async (op) => { const evidence = globalThis.prompt ? globalThis.prompt('Rollback evidence / reason') : ''; const idem = globalThis.prompt ? globalThis.prompt('Idempotency key') : ''; if (!evidence || !idem) return; try { state.operationResults.unshift(await api.rollbackOperation({ operationId: op.id, evidence, idempotencyKey: idem })); await loadOperations(); } catch (error) { state.error = error; render(); } };
  const loadOperations = async () => { if (!api.operations) return; state.operations = (await api.operations({ tenantId: state.selected?.tenant?.id || state.selected?.id || 'synthetic-tenant' })).data || []; };
  const renderTenants = (main) => { main.append(el('h2', 'Tenants')); if (!state.tenants.length) { main.append(el('p', 'No tenant metadata available.')); return; } const table = el('table'); table.setAttribute('aria-label', 'Tenant metadata'); const head = el('tr'); ['Name', 'Status', 'Organization'].forEach((v) => { const th = el('th', v); th.scope = 'col'; head.append(th); }); const thead = el('thead'); thead.append(head); table.append(thead); const body = el('tbody'); state.tenants.forEach((tenant) => { const row = el('tr'); const name = el('button', text(tenant.name)); name.type = 'button'; name.addEventListener('click', () => selectTenant(tenant.id)); const cell = el('td'); cell.append(name); row.append(cell, el('td', tenant.status), el('td', tenant.organization_id)); body.append(row); }); table.append(body); main.append(table); if (state.selected) { main.append(el('h3', `Tenant ${state.selected.tenant?.name || ''}`), el('p', `Projection: ${state.selected.projection?.status || 'unknown'}; indexed count: ${state.selected.projection?.indexed_count ?? 'unknown'}`)); const integration = state.integration; main.append(el('h4', 'Managed integration status')); if (!integration || integration.status === 'unavailable') main.append(el('p', 'Managed integration status unavailable (provider not configured or scope denied).')); else { const statusTable = el('table'); statusTable.setAttribute('aria-label', 'Managed integration status'); const statusBody = el('tbody'); ['observability', 'deployment', 'backup'].forEach((kind) => { const row = el('tr'); row.append(el('th', kind), el('td', integration[kind]?.status || 'unknown')); statusBody.append(row); }); statusTable.append(statusBody); main.append(statusTable); } } };
  const labels = { 'support-access': 'Support access broker', ingestion: 'Connector / ingestion fleet', 'canonical-quality': 'Canonical quality', 'search-projections': 'Search projections', redis: 'Redis health', 'ai-ops': 'AI operations', workflows: 'Workflow executions', 'policy-simulator': 'Policy simulator', security: 'Security', compliance: 'Compliance evidence', releases: 'Releases / flags', incidents: 'Incidents', audit: 'Audit', operations: 'Operations' };
  const renderModule = (main, name) => { main.append(el('h2', labels[name] || name.replace('-', ' '))); const data = state.moduleData[name]; if (!data || data.status === 'unavailable' || data.available === false) { const unavailable = el('p', `This module is unavailable: ${data?.reason || 'managed infrastructure is not configured or the requested scope is not authorized.'}`); unavailable.setAttribute('role', 'status'); main.append(unavailable); return; } const table = el('table'); table.setAttribute('aria-label', `${labels[name] || name} operational metadata`); const body = el('tbody'); Object.entries(data).filter(([key]) => !/secret|token|password|content|raw/i.test(key)).forEach(([key, value]) => { const row = el('tr'); row.append(el('th', key), el('td', typeof value === 'object' ? JSON.stringify(value) : text(value))); body.append(row); }); table.append(body); main.append(table); };
  const load = async () => { state.status = 'loading'; render(); try { if (!state.health) state.health = await api.health(); if (state.view === 'tenants' && !state.tenants.length) state.tenants = (await api.tenants()).data || []; if (state.view === 'operations') await loadOperations(); else if (modules.includes(state.view) && !state.moduleData[state.view]) state.moduleData[state.view] = await api.module(state.view); state.status = 'success'; } catch (error) { state.error = error; state.status = 'error'; } render(); };
  const selectTenant = async (id) => { state.status = 'loading'; render(); try { state.selected = await api.tenant(id); const environment = state.selected.environments?.[0]; if (environment && api.managedIntegrations) { try { state.integration = await api.managedIntegrations({ tenantId: id, environmentId: environment.id }); } catch (error) { state.integration = { status: 'unavailable', code: error.code }; } } state.status = 'success'; } catch (error) { state.error = error; state.status = 'error'; } render(); };
  render();
  return { load, selectTenant, snapshot: () => ({ ...state, tenants: [...state.tenants], operations: [...state.operations] }) };
}
