import test from 'node:test';
import assert from 'node:assert/strict';
import { createAdminApi, createAdminConsole } from './admin-console.mjs';
class Fake { constructor(tag) { this.tagName = tag.toUpperCase(); this.children = []; this.listeners = {}; this.textContent = ''; this.attributes = {}; this.value = ''; } append(...v) { this.children.push(...v); } replaceChildren(...v) { this.children = v; } setAttribute(k, v) { this.attributes[k] = String(v); } addEventListener(k, fn) { this.listeners[k] = fn; } }
globalThis.document = { createElement: (tag) => new Fake(tag) };
const root = () => new Fake('section');
test('admin API uses documented redacted endpoints and support header', async () => { let request; const api = createAdminApi({ baseUrl: 'https://api.test', supportSession: 'case-1', fetchImpl: async (url, options) => { request = { url, options }; return { ok: true, status: 200, json: async () => ({ data: [], page: { next_cursor: null } }) }; } }); await api.tenants({ limit: 500 }); assert.match(request.url, /\/admin\/v1\/tenants\?limit=100/); assert.equal(request.options.credentials, 'include'); assert.equal(request.options.headers['X-Support-Session'], 'case-1'); });
test('console loads dashboard and tenant data through adapter only', async () => { const calls = []; const api = { health: async () => { calls.push('health'); return { status: 'healthy', components: {} }; }, tenants: async () => { calls.push('tenants'); return { data: [{ id: 't1', name: 'Synthetic tenant', status: 'active', organization_id: 'o1' }] }; }, tenant: async () => ({ tenant: { name: 'Synthetic tenant' }, projection: { status: 'current', indexed_count: 1 } }) }; const app = createAdminConsole({ root: root(), api }); await app.load(); assert.deepEqual(calls, ['health']); assert.equal(app.snapshot().health.status, 'healthy'); });
test('forbidden errors are represented without leaking response payload', async () => { const app = createAdminConsole({ root: root(), api: { health: async () => { throw Object.assign(new Error('secret'), { status: 403, code: 'forbidden' }); } } }); await app.load(); assert.equal(app.snapshot().status, 'error'); assert.equal(app.snapshot().error.status, 403); });
test('operational modules and managed integrations use API seams', async () => { const paths = []; const api = { health: async () => ({ status: 'healthy', components: {} }), module: async (name) => { paths.push(name); return { status: 'ready', token: 'must-not-render' }; }, tenants: async () => ({ data: [] }), managedIntegrations: async () => ({ observability: { status: 'healthy', data_classification: 'operational_metadata' } }) }; const app = createAdminConsole({ root: root(), api }); await app.load(); assert.deepEqual(paths, []); assert.equal(app.snapshot().moduleData.operations, undefined); });
