import test from 'node:test';
import assert from 'node:assert/strict';
import { createAdminApi, createAdminConsole } from './admin-console.mjs';
class Fake { constructor(tag) { this.tagName = tag.toUpperCase(); this.children = []; this.listeners = {}; this.textContent = ''; this.attributes = {}; this.value = ''; } append(...v) { this.children.push(...v); } replaceChildren(...v) { this.children = v; } setAttribute(k, v) { this.attributes[k] = String(v); } addEventListener(k, fn) { this.listeners[k] = fn; } }
globalThis.document = { createElement: (tag) => new Fake(tag) };
const root = () => new Fake('section');
test('admin API uses documented redacted endpoints and support header', async () => { let request; const api = createAdminApi({ baseUrl: 'https://api.test', supportSession: 'case-1', fetchImpl: async (url, options) => { request = { url, options }; return { ok: true, status: 200, json: async () => ({ data: [], page: { next_cursor: null } }) }; } }); await api.tenants({ limit: 500 }); assert.match(request.url, /\/admin\/v1\/tenants\?limit=100/); assert.equal(request.options.credentials, 'include'); assert.equal(request.options.headers['X-Support-Session'], 'case-1'); });
test('console loads dashboard and tenant data through adapter only', async () => { const calls = []; const api = { health: async () => { calls.push('health'); return { status: 'healthy', components: {} }; }, tenants: async () => { calls.push('tenants'); return { data: [{ id: 't1', name: 'Synthetic tenant', status: 'active', organization_id: 'o1' }] }; }, tenant: async () => ({ tenant: { name: 'Synthetic tenant' }, projection: { status: 'current', indexed_count: 1 } }) }; const app = createAdminConsole({ root: root(), api }); await app.load(); assert.deepEqual(calls, ['health']); assert.equal(app.snapshot().health.status, 'healthy'); });
test('forbidden errors are represented without leaking response payload', async () => { const app = createAdminConsole({ root: root(), api: { health: async () => { throw Object.assign(new Error('secret'), { status: 403, code: 'forbidden' }); } } }); await app.load(); assert.equal(app.snapshot().status, 'error'); assert.equal(app.snapshot().error.status, 403); });
test('operational modules and managed integrations use API seams', async () => { const paths = []; const api = { health: async () => ({ status: 'healthy', components: {} }), module: async (name) => { paths.push(name); return { status: 'ready', token: 'must-not-render' }; }, tenants: async () => ({ data: [] }), managedIntegrations: async () => ({ observability: { status: 'healthy', data_classification: 'operational_metadata' } }) }; const app = createAdminConsole({ root: root(), api }); await app.load(); assert.deepEqual(paths, []); assert.equal(app.snapshot().moduleData.operations, undefined); });
test('managed integration route is explicit and bounded', async () => { let url; const api = createAdminApi({ baseUrl: 'https://api.test', fetchImpl: async (requestUrl) => { url = requestUrl; return { ok: true, status: 200, json: async () => ({ tenant_id: 't', environment_id: 'e', data_classification: 'operational_metadata', observability: { status: 'healthy' }, deployment: { status: 'unknown' }, backup: { status: 'healthy' } }) }; } }); const result = await api.managedIntegrations({ tenantId: 't', environmentId: 'e' }); assert.match(url, /^https:\/\/api\.test\/admin\/v1\/managed-integrations\?tenant_id=t&environment_id=e$/); assert.equal(result.data_classification, 'operational_metadata'); });
test('administrative operation lifecycle uses documented API paths and idempotency', async () => { const requests = []; const api = createAdminApi({ baseUrl: 'https://api.test', fetchImpl: async (url, options) => { requests.push({ url, options }); return { ok: true, status: 200, json: async () => ({ data: [], operation: { id: 'op1', status: 'approved' } }) }; } }); await api.operations({ tenantId: 't', environmentId: 'e' }); await api.createOperation({ tenantId: 't', environmentId: 'e', type: 'replay', reason: 'synthetic test reason', idempotencyKey: 'create-key-123456' }); await api.approveOperation({ operationId: 'op1', reason: 'independent approval reason', dualControl: true, idempotencyKey: 'approve-key-123456' }); await api.executeOperation({ operationId: 'op1', idempotencyKey: 'execute-key-123456' }); await api.rollbackOperation({ operationId: 'op1', evidence: 'synthetic rollback evidence', idempotencyKey: 'rollback-key-123456' }); assert.match(requests[0].url, /\/admin\/v1\/operations\?tenant_id=t&environment_id=e$/); assert.equal(requests[1].options.headers['Idempotency-Key'], 'create-key-123456'); assert.match(requests[2].url, /operations\/op1\/approve$/); assert.match(requests[3].url, /operations\/op1\/execute$/); assert.match(requests[4].url, /operations\/op1\/rollback$/); });
test('operations view loads records and keeps production execution fail-closed', async () => { const api = { health: async () => ({ status: 'healthy', components: {} }), operations: async () => ({ data: [{ id: 'op1', tenant_id: 't', environment_id: 'e', status: 'approved', managed_credentials_available: false, external_approval: false }] }) }; const host = root(); const app = createAdminConsole({ root: host, api }); const operationsButton = host.children[1].children.find((node) => node.textContent === 'operations'); operationsButton.listeners.click(); await new Promise((resolve) => setTimeout(resolve, 0)); assert.equal(app.snapshot().operations[0].id, 'op1'); assert.match(flatten(host), /managed credentials and explicit external approval/); });
test('normative admin modules are all reachable through documented redacted API routes', async () => { const names = ['support-access', 'ingestion', 'canonical-quality', 'search-projections', 'redis', 'ai-ops', 'workflows', 'policy-simulator', 'security', 'compliance', 'releases', 'incidents', 'audit', 'operations']; const paths = []; const api = createAdminApi({ baseUrl: 'https://api.test', fetchImpl: async (url) => { paths.push(url); return { ok: true, status: 200, json: async () => ({ status: 'unavailable', reason: 'synthetic provider not configured' }) }; } }); for (const name of names) await api.module(name); assert.deepEqual(paths.map((p) => p.replace('https://api.test', '')), names.map((n) => `/admin/v1/${n}`)); assert.throws(() => api.module('database-direct'), /unsupported_admin_module/); });
test('unavailable module state is truthful and does not render sensitive metadata', async () => { const host = root(); const api = { health: async () => ({ status: 'healthy', components: {} }), module: async () => ({ status: 'unavailable', reason: 'managed Redis provider not configured', token: 'secret-token' }) }; const app = createAdminConsole({ root: host, api }); const button = host.children[1].children.find((node) => node.textContent === 'redis'); button.listeners.click(); await new Promise((resolve) => setTimeout(resolve, 0)); assert.match(flatten(host), /managed Redis provider not configured/); assert.doesNotMatch(flatten(host), /secret-token/); assert.equal(app.snapshot().status, 'success'); });
function flatten(node) { return (node.textContent || '') + (node.children || []).map(flatten).join(''); }
